//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFA_WowDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public int SkillID { get; set; }
        public int RaceID { get; set; }
        public int ClassID { get; set; }
        public string SkillName { get; set; }
        public int SkillPower { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Race Race { get; set; }
    }
}
